### PR TITLE
Don't require span env to be specified

### PR DESCRIPTION
**Pull request by GregMefford**
Related to https://github.com/spandex-project/spandex/pull/75
With Datadog, if you don't specify an env in the application like this, it will use the env configured in the trace collector agent. This PR makes it possible to do so by not sending that key unless it's set.

### CODE REVIEW

**Comment by zachdaniel** [comment]
Looks good :) merge at you're liesure.

**Comment by GregMefford** [comment]
I'm not an authorized user for this branch. 😭 😉

**Comment by zachdaniel** [comment]
Weird, it says that you have write access on the dashboard.

**Comment by zachdaniel** [comment]
I can cut releases for these tomorrow also.

**Comment by GregMefford** [comment]
I was thinking we’d get the other in-flight PRs figured out and merged before we release again, but it’s up to you.

**Comment by zachdaniel** [comment]
Yeah, totally fine waiting, I really just meant that I wasn't going to do it last night :)

**Pull request merged**
