### PR TITLE
improvement: add `:flush` call

### PR DESCRIPTION
**Pull request by zachdaniel**

### CODE REVIEW

**Comment by GregMefford** [comment]
I'm curious what the use-case is here... is this so that you can synchronize in a test or something that the `APIServer` has processed a previous message?

**Comment by zachdaniel** [comment]
It came from a conversation in slack that is unfortunately gone, but IIRC it had to do with someone who was starting the Datadog API Server in a process (e.g not using application + supervision tree) and it was transient. It may have been being started in testing? And the problem was that things would shut down and the API Server would shut down before sending all messages. So the idea here was to have a synchronous `:flush` call that would let you wait on it to be done.

**Comment by GregMefford** [comment]
I think if we are going to do this, we'd want to also add a public API function to essentially allow people to flush the `waiting_traces` even if the `batch_size` has not been reached, rather than just making an internal GenServer `handle_call` that people would need to know how to use. I'm not sure what exactly the use-case was for this original PR, but I feel like that could be a useful feature and might meet the same need.

**Comment by SophisticaSean** [comment]
I think this is worthwhile. I'm running cron jobs in production that quickly spin up my supervision tree, do something, and then exit. It took me a lot of debugging to discover that `batch_size` was the reason I was getting orphaned traces. This should be a top level API call so that I can call `Tracer.flush`. Or/also, this should respond to a `Application.stop` signal and call flush as part of the cleanup. As it stands, if the application is asked to gracefully shutdown then spandex_datadog will eat any traces currently in the batch.

**Comment by SophisticaSean** [comment]
This is also an issue in the context of frequent deploys. Anytime an application is given a `SIGTERM`, it will gracefully shutdown but spandex_datadog will eat any traces currently left in the batch as well. So if you do frequent deploys in a given day you'll have a lot of missing or even orphaned trace's who's parent spans were consumed 😢

**Comment by SophisticaSean** [comment]
I've resolved my issue in #34

**Comment by zachdaniel** [comment]
This is no longer necessary because it now flushes itself on shutdown thanks to #34

**Pull request closed without merging**
