### PR TITLE
feat: add support for app analytics

### PR DESCRIPTION
**Pull request by baquiax**
One of the most useful features of DataDog is the App Analytcs
https://docs.datadoghq.com/tracing/app_analytics. It allows you
track the 100% of your traces to have a full visilibity about
what's going on.

We add this new feature to support it. You only need to add in
the tags the key-value: `:analytics_event: true`.

### CODE REVIEW

**Comment by baquiax** [comment]
@zachdaniel @GregMefford  I hope this PR accomplish the standard on the package.

**Comment by zachdaniel** [comment]
@baquiax this looks good to me, have you had a chance to confirm that it works as expected in datadog?

**Comment by baquiax** [comment]
Thanks for reply @zachdaniel 

Yes, I did. Here I attach a screen of my last tests. 

image

**Comment by zachdaniel** [comment]
Thank you for your contribution!

**Comment by baquiax** [comment]
You are welcome @zachdaniel , thanks to you for build this project. I'll create another PR adding examples of how to use this dep.

**Comment by GregMefford** [comment]
Thank you so much for taking the time to fix and test this! I’ve been meaning to look into this for a long time and just haven’t gotten the time yet! 🚀❤️

**Pull request merged**
